name: Build LaTeX Resume

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          args: -output-directory=build
          
      - name: Copy PDF to root for GitHub Pages (optional)
        run: cp build/main.pdf ./main.pdf
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: Resume
          path: build/main.pdf
          
      - name: Commit PDF to root for easy access
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add main.pdf
          git commit -m "Update PDF resume" || echo "No changes to commit"
          git push